language: java
jdk:
  - openjdk11
sudo: false # faster build

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
     - coderilya@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
